var a = 5;
var b = 10;
console.log("Is ".concat(a, " equal to ").concat(b, "? I predict False."));
console.log(a == b);
console.log("Is ".concat(a, " not equal to ").concat(b, "? I predict True."));
console.log(a != b);
console.log("Is ".concat(a, " less than ").concat(b, "? I predict True."));
console.log(a < b);
console.log("Is ".concat(a, " greater than ").concat(b, "? I predict False."));
console.log(a > b);
console.log("Is ".concat(a, " less than or equal to ").concat(b, "? I predict True."));
console.log(a <= b);
console.log("Is ".concat(a, " greater than or equal to ").concat(b, "? I predict False."));
console.log(a >= b);
var str1 = "hello";
var str2 = "HELLO";
console.log("Is ".concat(str1, " equal to ").concat(str2, " ignoring case? I predict True."));
console.log(str1.toUpperCase() == str2.toUpperCase());
console.log("Is ".concat(str1, " equal to ").concat(str2, "? I predict False."));
console.log(str1 == str2);
var bool1 = true;
var bool2 = false;
console.log("Is ".concat(bool1, " AND ").concat(bool2, " true? I predict False."));
console.log(bool1 && bool2);
console.log("Is ".concat(bool1, " OR ").concat(bool2, " true? I predict True."));
console.log(bool1 || bool2);
